version: "2.4"

services:
  gitlab-omnibus:
    restart: always
    image: gitlab/gitlab-ee:13.12.3-ee.0
    depends_on:
      - redis
      - db
    ports:
      - '80:80'
      - '22:22'
      - '443:443'
    volumes:
      - '/Users/home/gitlab/config:/etc/gitlab'
      - '/Users/home/gitlab/logs:/var/log/gitlab'
      - '/Users/home/gitlab/data:/var/opt/gitlab'
    healthcheck:
      test: [ 'CMD', '/usr/local/sbin/healthcheck' ]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # each config in one line
        external_url 'http://gitlab'
        # postgresql
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        gitlab_rails['db_host'] = 'db'
        gitlab_rails['db_port'] = 5432
        gitlab_rails['db_username'] = '${POSTGRES_DB_NAME}'
        gitlab_rails['db_password'] = '${POSTGRES_DB_PASSWORD}'

        # redis
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = 6379
