version: "2.3"

services:
  gitlab:
    restart: always
    image: ${GITLAB_VERSION}
    scale: 2
    volumes:
      - "./gitlab-secrets.json:/etc/gitlab/gitlab-secrets.json"
      - "/Users/home/gitlab/data:/var/opt/gitlab"
    links:
      - "redis"
      - "postgresql"
      - "gitaly"
    depends_on:
      - "redis"
      - "postgresql"
      - "gitaly"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_URL}'

        # Avoid running unnecessary services
        gitaly['enable'] = false
        postgresql['enable'] = false
        prometheus['enable'] = false
        alertmanager['enable'] = false
        grafana['enable'] = false
        gitlab_exporter['enable'] = false

        gitlab_rails['gitaly_token'] = '${GITALY_AUTH_TOKEN}'
        gitlab_shell['secret_token'] = '${GITALY_SECRET_TOKEN}'

        git_data_dirs({
          'default' => { 'gitaly_address' => 'tcp://gitaly:8075' },
        })

        ## Disable components that will not be on the GitLab application server
        roles ['application_role']
        nginx['enable'] = true

        ## PostgreSQL connection details
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_encoding'] = "unicode"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_username'] = "${POSTGRES_DB_USERNAME}"
        gitlab_rails['db_password'] = "${POSTGRES_DB_PASSWORD}"

        ## Redis connection details
        gitlab_rails['redis_host'] = "redis"
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_password'] = "${REDIS_PASSWORD}"

        # Set the network addresses that the exporters used for monitoring will listen on
        node_exporter['listen_address'] = "0.0.0.0:9100"
        gitlab_workhorse['prometheus_listen_addr'] = "0.0.0.0:9229"
        sidekiq['listen_address'] = "0.0.0.0"
        # Set number of Sidekiq threads per queue process to the recommend number of 10
        sidekiq['max_concurrency'] = 10
        puma['listen'] = "0.0.0.0"
