version: "2.3"

services:
  gitlab:
    restart: always
    image: ${GITLAB_VERSION}
    scale: 2
    volumes:
      - "./config/global/gitlab-secrets.json:/etc/gitlab/gitlab-secrets.json"
      - "./config/global/ssh_host_ecdsa_key:/etc/gitlab/ssh_host_ecdsa_key"
      - "./config/global/ssh_host_ecdsa_key.pub:/etc/gitlab/ssh_host_ecdsa_key.pub"
      - "./config/global/ssh_host_ed25519_key:/etc/gitlab/ssh_host_ed25519_key"
      - "./config/global/ssh_host_ed25519_key.pub:/etc/gitlab/ssh_host_ed25519_key.pub"
      - "./config/global/ssh_host_rsa_key:/etc/gitlab/ssh_host_rsa_key"
      - "./config/global/ssh_host_rsa_key.pub:/etc/gitlab/ssh_host_rsa_key.pub"

      # we don't want to mount the entire /var/opt/gitlab since the socket files are managed there as well
      - "/Users/home/gitlab/data/git-data:/var/opt/gitlab/git-data"
      - "/Users/home/gitlab/data/gitlab-ci:/var/opt/gitlab/gitlab-ci"
    links:
      - "redis"
      - "postgresql"
      - "gitaly"
    depends_on:
      - "redis"
      - "postgresql"
      - "gitaly"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_URL}'

        # Avoid running unnecessary services
        gitaly['enable'] = false
        postgresql['enable'] = false
        prometheus['enable'] = false
        alertmanager['enable'] = false
        grafana['enable'] = false
        gitlab_exporter['enable'] = false
        sidekiq['enable'] = false

        # Service configs
        roles ['application_role']
        nginx['enable'] = true

        # Set the network addresses that the exporters used for monitoring will listen on
        node_exporter['listen_address'] = "0.0.0.0:9100"
        gitlab_workhorse['prometheus_listen_addr'] = "0.0.0.0:9229"
        puma['listen'] = "0.0.0.0"

        gitlab_rails['auto_migrate'] = false
        ## PostgreSQL connection details
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_encoding'] = "unicode"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_username'] = "${POSTGRES_DB_USERNAME}"
        gitlab_rails['db_password'] = "${POSTGRES_DB_PASSWORD}"

        ## Redis connection details
        gitlab_rails['redis_host'] = "redis"
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_password'] = "${REDIS_PASSWORD}"

        # Gitaly connection details
        gitlab_rails['gitaly_token'] = '${GITALY_AUTH_TOKEN}'
        git_data_dirs({
          'default' => { 'gitaly_address' => 'tcp://gitaly:8075' },
        })
