version: "2.3"

services:
  sidekiq:
    restart: always
    image: ${GITLAB_VERSION}
    links:
      - "redis"
      - "postgresql"
    depends_on:
      - "redis"
      - "postgresql"
    volumes:
      - "./config/global/gitlab-secrets.json:/etc/gitlab/gitlab-secrets.json"
      - "${GITLAB_DATA_FOLDER}:/var/opt/gitlab"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${GITLAB_URL}'

        # Avoid running unnecessary services
        alertmanager['enable'] = false
        gitaly['enable'] = false
        puma['enable'] = false
        gitlab_workhorse['enable'] = false
        patroni['enable'] = false
        postgresql['enable'] = false
        consul['enable'] = false
        prometheus['enable'] = false
        alertmanager['enable'] = false
        pgbouncer_exporter['enable'] = false
        redis['enable'] = false
        redis_exporter['enable'] = false
        grafana['enable'] = false
        gitlab_exporter['enable'] = false
        nginx['enable'] = false

        # Service configs
        sidekiq['enable'] = true
        sidekiq['listen_address'] = "0.0.0.0"
        sidekiq['max_concurrency'] = 10

        gitlab_rails['auto_migrate'] = false

        ## PostgreSQL connection details
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_encoding'] = "unicode"
        gitlab_rails['db_host'] = "postgresql"
        gitlab_rails['db_username'] = "${POSTGRES_DB_USERNAME}"
        gitlab_rails['db_password'] = "${POSTGRES_DB_PASSWORD}"

        ## Redis connection details
        gitlab_rails['redis_host'] = "redis"
        gitlab_rails['redis_port'] = 6379
        gitlab_rails['redis_password'] = "${REDIS_PASSWORD}"

        # Gitaly connection details
        gitlab_rails['gitaly_token'] = '${GITALY_AUTH_TOKEN}'
        git_data_dirs({
          'default' => { 'gitaly_address' => 'tcp://gitaly:8075' },
        })
